apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: cm-team
  description: The Constituent Mastering Team
spec:
  type: team
  profile:
    displayName: CM Team
    email: cmteam@example.com
    picture: https://example.com/groups/bu-infrastructure.jpeg

